export const SAMPLE_UNIVERSITIES = [
  {
    id: 1,
    name: "Technical University of Munich",
    city: "Munich",
    state: "Bavaria",
    ranking: 1,
    program: "M.Sc. Computer Science",
    deadline: "2025-07-15",
    status: "Applied",
    tuition: "Free (€72 semester fee)",
    language: "English",
    gpaRequired: "3.5",
    ieltsRequired: "7.0",
    website: "https://www.tum.de",
    notes: "Top technical university. Strong industry connections.",
    documents: ["Transcript", "CV", "Motivation Letter", "Language Certificate", "Bachelor Certificate"],
    tags: ["Technical", "Top 10", "English Program"],
  },
  {
    id: 2,
    name: "Ludwig Maximilian University",
    city: "Munich",
    state: "Bavaria",
    ranking: 2,
    program: "M.Sc. Data Science",
    deadline: "2025-05-31",
    status: "Researching",
    tuition: "Free (€85 semester fee)",
    language: "English",
    gpaRequired: "3.3",
    ieltsRequired: "6.5",
    website: "https://www.lmu.de",
    notes: "Excellence university. Great research opportunities.",
    documents: ["Transcript", "CV", "Motivation Letter", "Reference Letters", "Language Certificate"],
    tags: ["Research", "Excellence Initiative"],
  },
  {
    id: 3,
    name: "RWTH Aachen University",
    city: "Aachen",
    state: "North Rhine-Westphalia",
    ranking: 3,
    program: "M.Sc. Computer Engineering",
    deadline: "2025-09-01",
    status: "Wishlist",
    tuition: "Free (€310 semester fee)",
    language: "English/German",
    gpaRequired: "3.2",
    ieltsRequired: "6.5",
    website: "https://www.rwth-aachen.de",
    notes: "Strong engineering faculty. Near Belgium & Netherlands.",
    documents: ["Transcript", "CV", "Statement of Purpose", "Language Certificate"],
    tags: ["Engineering", "Research"],
  },
  {
    id: 4,
    name: "Heidelberg University",
    city: "Heidelberg",
    state: "Baden-Württemberg",
    ranking: 4,
    program: "M.Sc. Bioinformatics",
    deadline: "2025-06-15",
    status: "Rejected",
    tuition: "Free (€162 semester fee)",
    language: "English",
    gpaRequired: "3.7",
    ieltsRequired: "7.5",
    website: "https://www.uni-heidelberg.de",
    notes: "Oldest German university. Very competitive.",
    documents: ["Transcript", "CV", "Research Statement", "Language Certificate", "Reference Letters"],
    tags: ["Sciences", "Competitive", "Historic"],
  },
  {
    id: 5,
    name: "Humboldt University Berlin",
    city: "Berlin",
    state: "Berlin",
    ranking: 5,
    program: "M.Sc. Computer Science",
    deadline: "2025-08-01",
    status: "Accepted",
    tuition: "Free (€309 semester fee)",
    language: "English",
    gpaRequired: "3.0",
    ieltsRequired: "6.5",
    website: "https://www.hu-berlin.de",
    notes: "Vibrant city. Great startup ecosystem.",
    documents: ["Transcript", "CV", "Motivation Letter", "Language Certificate"],
    tags: ["Berlin", "Tech Hub", "Startups"],
  },
  {
    id: 6,
    name: "University of Hamburg",
    city: "Hamburg",
    state: "Hamburg",
    ranking: 8,
    program: "M.Sc. Artificial Intelligence",
    deadline: "2025-10-15",
    status: "Researching",
    tuition: "Free (€350 semester fee)",
    language: "English",
    gpaRequired: "3.0",
    ieltsRequired: "6.5",
    website: "https://www.uni-hamburg.de",
    notes: "Port city. Growing tech scene.",
    documents: ["Transcript", "CV", "Motivation Letter", "Language Certificate"],
    tags: ["AI Focus", "Port City"],
  },
];

export const STATUS_CONFIG = {
  Wishlist: { color: "#64748b", bg: "rgba(100,116,139,0.15)", icon: "⭐", label: "Wishlist" },
  Researching: { color: "#06b6d4", bg: "rgba(6,182,212,0.15)", icon: "🔍", label: "Researching" },
  Applied: { color: "#8b5cf6", bg: "rgba(139,92,246,0.15)", icon: "📤", label: "Applied" },
  Accepted: { color: "#10b981", bg: "rgba(16,185,129,0.15)", icon: "✅", label: "Accepted" },
  Rejected: { color: "#ef4444", bg: "rgba(239,68,68,0.15)", icon: "❌", label: "Rejected" },
  Waitlisted: { color: "#f59e0b", bg: "rgba(245,158,11,0.15)", icon: "⏳", label: "Waitlisted" },
};

export const ALL_STATUSES = Object.keys(STATUS_CONFIG);

export const REQUIRED_DOCUMENTS = [
  { id: "transcript", label: "Academic Transcript", icon: "📄", note: "Official, translated if needed" },
  { id: "cv", label: "Curriculum Vitae", icon: "👤", note: "Max 2 pages, EU format preferred" },
  { id: "motivation", label: "Motivation Letter", icon: "✍️", note: "1–2 pages, university-specific" },
  { id: "language", label: "Language Certificate", icon: "🌐", note: "IELTS/TOEFL/TestDaF" },
  { id: "bachelor", label: "Bachelor's Certificate", icon: "🎓", note: "Notarized copy" },
  { id: "passport", label: "Passport Copy", icon: "🪪", note: "Valid for duration of studies" },
  { id: "references", label: "Reference Letters", icon: "💌", note: "2–3 academic references" },
  { id: "portfolio", label: "Portfolio / Work Samples", icon: "🗂️", note: "If applicable" },
  { id: "financials", label: "Financial Proof", icon: "💰", note: "€11,208+/year blocked account" },
  { id: "aPS", label: "APS Certificate", icon: "🏛️", note: "Required for Indian students" },
];
